version: 0.2

phases:
  install:
    commands:
      - cd app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://shuhei-portfolio.jp --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'